theme: jekyll-theme-midnight
page_title: Devblog | Alex Butler Games
title: Alex Butler Games
description: Updates & insights on current projects, game design and programming
google_analytics: UA-100809402-1

defaults:
- scope:
    path: "" # all
  values:
    layout: default
    author: Alex Butler
    catagories: gamedev

exclude:
- node_modules
- gulpfile.js
- package.json
- README.md
