theme: jekyll-theme-midnight
page_title: Devblog | Robo Instructus | Alex Butler Games
title: Robo Instructus devblog
description: Updates the development of Robo Instructus and the other games and projects of Alex Butler
google_analytics: UA-100809402-1

defaults:
- scope:
    path: "" # all
  values:
    layout: default
    author: Alex Butler
    catagories: gamedev

exclude:
- node_modules
- gulpfile.js
- package.json
- README.md
- package-lock.json
- publish-drafts

plugins:
- jekyll-feed
